# Generated by Django 5.2.17 on 2026-08-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loanapplication_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
